#!/bin/bash
pypy uoj.py 5555 >worker.1.log 2>worker.1.log &
pypy uoj.py 6666 >worker.2.log 2>worker.2.log &
pypy uoj.py 7777 >worker.3.log 2>worker.3.log &
pypy uoj.py 8888 >worker.4.log 2>worker.4.log &
pypy server.py >server.log 2>server.log &
